### ISSUE TITLE
scene with separate left and right eye canvases

### ISSUE THREAD

**Issue by andreasplesch** [toji/webvr-samples#22]
WebVR allows using two separate canvases one for the right eye and one for the left eye. 
Although perhaps less performant, such a setup may be more convenient and seem more natural for some.
Please consider adding a static, stereoscopic scene using this approach.

**Comment by toji** [comment]
The WebVR spec as it exists today does not allow for separate canvases per-eye, only customizing the viewports within the canvas that are used. (You wouldn't want to use a separate canvas anyway, since that would require duplication of 3D resources.) Future spec revisions may change that, but for now it won't work.

**Comment by andreasplesch** [comment]
Thanks for the quick response.
I was under the impression that one could have multiple layers being presented by the vrdevice, implied by the plural in getLayers() and the word layer suggesting a stack of superimposed images.
So I thought one layer could be for the right eye with the left empty and one layer for the left eye with the right eye empty.
Could you clarify ?

**Comment by andreasplesch** [comment]
Hi Chris j
